{"name": "test_logout", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.fill: Timeout 30000ms exceeded.\nCall log:\n  - waiting for locator(\"input[name='username']\")", "trace": "login_page = <pages.login_page.LoginPage object at 0x000001C2972E0640>\n\n    def test_logout(login_page):\n        login_page.navigate(\"https://takenote.dev/app\")\n>       login_page.enter_username(\"testuser\")\n\ntests\\test_login.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\login_page.py:12: in enter_username\n    self.page.fill(self.username_input, username)\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:10136: in fill\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:866: in fill\n    return await self._main_frame.fill(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:527: in fill\n    await self._channel.send(\"fill\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x000001C2971CA660>\ncb = <function Channel.send.<locals>.<lambda> at 0x000001C2974A3B00>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.fill: Timeout 30000ms exceeded.\nE           Call log:\nE             - waiting for locator(\"input[name='username']\")\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "attachments": [{"name": "screenshot", "source": "fcae414f-dc55-4e82-8d88-394517ba2842-attachment.png", "type": "image/png"}], "start": 1741166329052, "stop": 1741166360114, "uuid": "93ec7c40-28cd-41bc-8b6e-25dbe9824d05", "historyId": "0de671ca3ce3dd4a72dc222ea17df7db", "testCaseId": "0de671ca3ce3dd4a72dc222ea17df7db", "fullName": "tests.test_login#test_logout", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-GIDTMH7"}, {"name": "thread", "value": "10884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}